const productsData = [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    price: 59.99,
    originalPrice: 79.99,
    image: "https://via.placeholder.com/400x500?text=Headphones",
    category: "electronics",
    rating: 4.5,
    reviewsCount: 112,
    isNew: true,
    isFeatured: true,
  },
  {
    id: 2,
    name: "Smart LED Desk Lamp",
    price: 29.99,
    image: "https://via.placeholder.com/400x500?text=Desk+Lamp",
    category: "home",
    rating: 4.2,
    reviewsCount: 45,
    isNew: false,
    isFeatured: true,
  },
  {
    id: 3,
    name: "Men's Casual Sneakers",
    price: 49.99,
    originalPrice: 69.99,
    image: "https://via.placeholder.com/400x500?text=Sneakers",
    category: "fashion",
    rating: 4.8,
    reviewsCount: 220,
    isNew: true,
    isFeatured: false,
  },
  {
    id: 4,
    name: "Stainless Steel Water Bottle",
    price: 19.99,
    image: "https://via.placeholder.com/400x500?text=Water+Bottle",
    category: "home",
    rating: 4.0,
    reviewsCount: 33,
    isNew: false,
    isFeatured: false,
  },
  {
    id: 5,
    name: "Women's Leather Handbag",
    price: 89.99,
    originalPrice: 120.0,
    image: "https://via.placeholder.com/400x500?text=Handbag",
    category: "fashion",
    rating: 4.6,
    reviewsCount: 88,
    isNew: true,
    isFeatured: true,
  },
  {
    id: 6,
    name: "Wireless Ergonomic Mouse",
    price: 25.99,
    image: "https://via.placeholder.com/400x500?text=Mouse",
    category: "electronics",
    rating: 4.3,
    reviewsCount: 52,
    isNew: false,
    isFeatured: false,
  },
  {
    id: 7,
    name: "Organic Face Cream",
    price: 15.99,
    image: "https://via.placeholder.com/400x500?text=Face+Cream",
    category: "beauty",
    rating: 4.7,
    reviewsCount: 77,
    isNew: true,
    isFeatured: false,
  },
  {
    id: 8,
    name: "Yoga Mat Non-Slip",
    price: 22.99,
    image: "https://via.placeholder.com/400x500?text=Yoga+Mat",
    category: "home",
    rating: 4.4,
    reviewsCount: 65,
    isNew: false,
    isFeatured: true,
  },
  {
    id: 9,
    name: "Bluetooth Smartwatch",
    price: 129.99,
    originalPrice: 149.99,
    image: "https://via.placeholder.com/400x500?text=Smartwatch",
    category: "electronics",
    rating: 4.6,
    reviewsCount: 140,
    isNew: true,
    isFeatured: true,
  },
  {
    id: 10,
    name: "Scented Candles Set",
    price: 18.99,
    image: "https://via.placeholder.com/400x500?text=Candles",
    category: "home",
    rating: 4.1,
    reviewsCount: 28,
    isNew: false,
    isFeatured: false,
  },
  // Add more if needed up to 20–30 items for testing
];

export default productsData;
