export interface Product {
  id: number;
  name: string;
  price: number;
  originalPrice?: number;
  image: string;
  category: "electronics" | "fashion" | "home" | "beauty";
  brand: string;
  rating: number;
  reviewsCount: number;
  isNew: boolean;
  isFeatured: boolean;
  inStock: boolean;
  onSale: boolean;
  isFavorite?: boolean;
}

const productsData: Product[] = [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    price: 59.99,
    originalPrice: 79.99,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80",
    category: "electronics",
    brand: "Auralux",
    rating: 4.5,
    reviewsCount: 112,
    isNew: true,
    isFeatured: true,
    inStock: true,
    onSale: true,
  },
  {
    id: 2,
    name: "Smart LED Desk Lamp",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1517999144091-3d9dca6d1e43?auto=format&fit=crop&w=800&q=80",
    category: "home",
    brand: "Lumora",
    rating: 4.2,
    reviewsCount: 45,
    isNew: false,
    isFeatured: true,
    inStock: true,
    onSale: false,
  },
  {
    id: 3,
    name: "Men's Casual Sneakers",
    price: 49.99,
    originalPrice: 69.99,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80",
    category: "fashion",
    brand: "StrideX",
    rating: 4.8,
    reviewsCount: 220,
    isNew: true,
    isFeatured: false,
    inStock: true,
    onSale: true,
  },
  {
    id: 4,
    name: "Stainless Steel Water Bottle",
    price: 19.99,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80",
    category: "home",
    brand: "Hydrify",
    rating: 4,
    reviewsCount: 33,
    isNew: false,
    isFeatured: false,
    inStock: true,
    onSale: false,
  },
  {
    id: 5,
    name: "Women's Leather Handbag",
    price: 89.99,
    originalPrice: 120,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80",
    category: "fashion",
    brand: "BelleRue",
    rating: 4.6,
    reviewsCount: 88,
    isNew: true,
    isFeatured: true,
    inStock: false,
    onSale: true,
  },
  {
    id: 6,
    name: "Wireless Ergonomic Mouse",
    price: 25.99,
    image: "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=800&q=80",
    category: "electronics",
    brand: "Auralux",
    rating: 4.3,
    reviewsCount: 52,
    isNew: false,
    isFeatured: false,
    inStock: true,
    onSale: false,
  },
  {
    id: 7,
    name: "Organic Face Cream",
    price: 15.99,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    category: "beauty",
    brand: "PureLeaf",
    rating: 4.7,
    reviewsCount: 77,
    isNew: true,
    isFeatured: false,
    inStock: true,
    onSale: false,
  },
  {
    id: 8,
    name: "Yoga Mat Non-Slip",
    price: 22.99,
    image: "https://images.unsplash.com/photo-1593811167562-9cef47bfc4d7?auto=format&fit=crop&w=800&q=80",
    category: "home",
    brand: "Hydrify",
    rating: 4.4,
    reviewsCount: 65,
    isNew: false,
    isFeatured: true,
    inStock: true,
    onSale: false,
  },
  {
    id: 9,
    name: "Bluetooth Smartwatch",
    price: 129.99,
    originalPrice: 149.99,
    image: "https://images.unsplash.com/photo-1510017803434-a899398421b3?auto=format&fit=crop&w=800&q=80",
    category: "electronics",
    brand: "Chronix",
    rating: 4.6,
    reviewsCount: 140,
    isNew: true,
    isFeatured: true,
    inStock: true,
    onSale: true,
  },
  {
    id: 10,
    name: "Scented Candles Set",
    price: 18.99,
    image: "https://images.unsplash.com/photo-1603006905393-cf42eb5817fd?auto=format&fit=crop&w=800&q=80",
    category: "home",
    brand: "Lumora",
    rating: 4.1,
    reviewsCount: 28,
    isNew: false,
    isFeatured: false,
    inStock: false,
    onSale: false,
  },
  {
    id: 11,
    name: "Vitamin C Serum",
    price: 24.99,
    originalPrice: 34.99,
    image: "https://images.unsplash.com/photo-1625772452859-1c03d5bf1137?auto=format&fit=crop&w=800&q=80",
    category: "beauty",
    brand: "PureLeaf",
    rating: 4.9,
    reviewsCount: 91,
    isNew: true,
    isFeatured: true,
    inStock: true,
    onSale: true,
  },
  {
    id: 12,
    name: "Minimalist Leather Wallet",
    price: 34.99,
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80",
    category: "fashion",
    brand: "BelleRue",
    rating: 4.2,
    reviewsCount: 41,
    isNew: false,
    isFeatured: false,
    inStock: true,
    onSale: false,
  },
];

export default productsData;
