export interface Product {
  id: number;
  name: string;
  price: number;
  originalPrice?: number;
  image: string;
  category: "desktops" | "laptops" | "printers" | "components";
  brand: string;
  rating: number;
  reviewsCount: number;
  isNew: boolean;
  isFeatured: boolean;
  inStock: boolean;
  onSale: boolean;
  isFavorite?: boolean;
}

const productsData: Product[] = [
  {
    id: 1,
    name: "Business Desktop Core i7",
    price: 899,
    originalPrice: 999,
    image: "https://images.unsplash.com/photo-1587831990711-23ca6441447b?auto=format&fit=crop&w=800&q=80",
    category: "desktops",
    brand: "Dell",
    rating: 4.6,
    reviewsCount: 112,
    isNew: true,
    isFeatured: true,
    inStock: true,
    onSale: true,
  },
  {
    id: 2,
    name: "Gaming Desktop RTX Edition",
    price: 1499,
    image: "https://images.unsplash.com/photo-1593640495253-23196b27a87f?auto=format&fit=crop&w=800&q=80",
    category: "desktops",
    brand: "Lenovo",
    rating: 4.8,
    reviewsCount: 85,
    isNew: true,
    isFeatured: true,
    inStock: true,
    onSale: false,
  },
  {
    id: 3,
    name: "Office Laptop 14-inch",
    price: 749,
    originalPrice: 829,
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80",
    category: "laptops",
    brand: "HP",
    rating: 4.5,
    reviewsCount: 204,
    isNew: false,
    isFeatured: true,
    inStock: true,
    onSale: true,
  },
  {
    id: 4,
    name: "Ultrabook Pro 13",
    price: 1199,
    image: "https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=800&q=80",
    category: "laptops",
    brand: "ASUS",
    rating: 4.7,
    reviewsCount: 77,
    isNew: true,
    isFeatured: false,
    inStock: true,
    onSale: false,
  },
  {
    id: 5,
    name: "All-in-One Inkjet Printer",
    price: 189,
    originalPrice: 229,
    image: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&w=800&q=80",
    category: "printers",
    brand: "Canon",
    rating: 4.2,
    reviewsCount: 56,
    isNew: false,
    isFeatured: true,
    inStock: true,
    onSale: true,
  },
  {
    id: 6,
    name: "Mono Laser Office Printer",
    price: 259,
    image: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=80",
    category: "printers",
    brand: "Brother",
    rating: 4.4,
    reviewsCount: 40,
    isNew: false,
    isFeatured: false,
    inStock: false,
    onSale: false,
  },
  {
    id: 7,
    name: "8GB DDR4 RAM Kit",
    price: 39,
    image: "https://images.unsplash.com/photo-1562976540-1502c2145186?auto=format&fit=crop&w=800&q=80",
    category: "components",
    brand: "Kingston",
    rating: 4.6,
    reviewsCount: 132,
    isNew: false,
    isFeatured: false,
    inStock: true,
    onSale: false,
  },
  {
    id: 8,
    name: "NVMe SSD 1TB",
    price: 89,
    originalPrice: 109,
    image: "https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=800&q=80",
    category: "components",
    brand: "Samsung",
    rating: 4.9,
    reviewsCount: 195,
    isNew: true,
    isFeatured: true,
    inStock: true,
    onSale: true,
  },
  {
    id: 9,
    name: "Desktop Repair Service Package",
    price: 129,
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
    category: "desktops",
    brand: "Triple S Service",
    rating: 4.8,
    reviewsCount: 68,
    isNew: false,
    isFeatured: true,
    inStock: true,
    onSale: false,
  },
  {
    id: 10,
    name: "Printer Maintenance Service",
    price: 79,
    image: "https://images.unsplash.com/photo-1555421689-491a97ff2040?auto=format&fit=crop&w=800&q=80",
    category: "printers",
    brand: "Triple S Service",
    rating: 4.5,
    reviewsCount: 53,
    isNew: false,
    isFeatured: false,
    inStock: true,
    onSale: false,
  },
];

export default productsData;
